### PR TITLE
Make xgettext respect granularity for sub-chapter messages

### PR DESCRIPTION
**Pull request by carreter**
Related to #171.

While trying to refresh the Spanish translation of Comprehensive Rust, @henrif75 noticed that the `messages.pot` file I generated had line numbers that shouldn't be there (see https://github.com/google/comprehensive-rust/issues/2120).

Digging around in the code, I noticed that the `xgettext` code was ignoring the granularity for sub-chapters. This PR fixes that!

### CODE REVIEW

**Comment by kdarkhan** [comment]
Thanks for the fix, @carreter! Can you add or update one of the existing test cases which will catch this bug please?

I think it will be good to have this tested to ensure we don't break it in the future.

**Comment by carreter** [comment]
Added the test as requested @kdarkhan !

**Review by kdarkhan — APPROVED** [review]

**Comment by kdarkhan** [comment]
Please fix formatting. LGTM otherwise.

**Comment by kdarkhan** [comment]
I added the fix on top of your PR, thanks for the contribution.

**Pull request merged**
